apiVersion: v1
kind: Service
metadata:
  name: lima
spec:
  ports:
  - port: 8080
    targetPort: 5678
  type: ClusterIP
  selector:
    app: lima
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lima
spec:
  selector:
    matchLabels:
      app: lima
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: lima
        version: "1.0"
    spec:
      containers:
      - name: lima
        image: hashicorp/http-echo
        args:
        - "-text=lima v1"
        ports:
        - containerPort: 5678
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: lima
spec:
  parentRefs:
  - name: shared-gateway
    namespace: infra-ns
  rules:
  - matches:
    - path:
        value: /lima
    backendRefs:
    - name: lima
      port: 8080
