apiVersion: v1
kind: Service
metadata:
  name: REPLACE_NAMESPACE_NAME
spec:
  ports:
  - port: 8080
    targetPort: 5678
  type: ClusterIP
  selector:
    app: REPLACE_NAMESPACE_NAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: REPLACE_NAMESPACE_NAME
spec:
  selector:
    matchLabels:
      app: REPLACE_NAMESPACE_NAME
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: REPLACE_NAMESPACE_NAME
        version: "1.0"
    spec:
      containers:
      - name: REPLACE_NAMESPACE_NAME
        image: hashicorp/http-echo
        args:
        - "-tetx=REPLACE_NAMESPACE_NAME v1"
        ports:
        - containerPort: 5678
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: REPLACE_NAMESPACE_NAME
spec:
  parentRefs:
  - name: shared-gateway
    namespace: infra-ns
  rules:
  - matches:
    - path:
        value: /REPLACE_NAMESPACE_NAME
    backendRefs:
    - name: REPLACE_NAMESPACE_NAME
      port: 8080
